'use client';

// ═══════════════════════════════════════════════════════════
//  MANTRA REEL DATASET
//  videoSrc = this IS a content video (plays as video reel)
//  no videoSrc = audio-only, uses imageBg + wave ring animation
// ═══════════════════════════════════════════════════════════
export interface MantraReel {
    id: string;
    name: string;
    nameHi: string;
    deity: string;
    deityHi: string;
    mantraText: string;
    transliteration: string;
    meaning: string;
    color: string;
    secondColor: string;
    audioSrc: string;
    videoSrc?: string;   // Only set when the reel IS a video
    imageBg: string;
    durationLabel: string;
    isLong: boolean;
    category: string;
    emoji: string;
}

export const MANTRA_REELS: MantraReel[] = [
    {
        id: 'gayatri-deep',
        name: 'Gayatri Mantra',
        nameHi: 'गायत्री मंत्र (घनपाठ)',
        deity: 'Savitri — Divine Sun',
        deityHi: 'सविता — दिव्य सूर्य',
        mantraText: 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं\nभर्गो देवस्य धीमहि\nधियो यो नः प्रचोदयात् ॥',
        transliteration: 'Om Bhur Bhuva Swah — Tat Savitur Varenyam',
        meaning: 'We meditate on the divine light of the Sun — may it illuminate our minds',
        color: '#fbbf24',
        secondColor: '#f97316',
        audioSrc: 'https://ik.imagekit.io/rcsesr4xf/gayatri-mantra-ghanpaath.mp3',
        imageBg: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~4 min',
        isLong: false,
        category: 'Vedic Mantra',
        emoji: '☀️',
    },
    {
        id: 'lalitha-sahasranamam',
        name: 'Lalitha Sahasranamam',
        nameHi: 'ललिता सहस्रनाम',
        deity: 'Lalitha — Divine Mother',
        deityHi: 'ललिता — दिव्य माता',
        mantraText: 'ॐ ऐं ह्रीं क्लीं\nत्रिपुरसुन्दर्यै नमः\nश्री महात्रिपुर सुन्दरी',
        transliteration: 'Om Aim Hreem Kleem — Tripurasundaryai Namah',
        meaning: 'A thousand names of the Divine Mother — the beautiful one of three cities',
        color: '#f472b6',
        secondColor: '#a21caf',
        audioSrc: 'https://ik.imagekit.io/rcsesr4xf/Lalitha-Sahasranamam.mp3',
        imageBg: '/images/mata%20lalitha.jpg',
        durationLabel: '~45 min',
        isLong: true,
        category: 'Stotra',
        emoji: '🌸',
    },
    {
        id: 'shiva-tandava',
        name: 'Shiva Tandava Stotram',
        nameHi: 'शिव तांडव स्तोत्रम्',
        deity: 'Mahadev — Lord Shiva',
        deityHi: 'महादेव — भगवान शिव',
        mantraText: 'जटाटवीगलज्जलप्रवाहपावितस्थले\nगलेऽवलम्ब्य लम्बितां भुजङ्गतुङ्गमालिकाम् ॥',
        transliteration: 'Jatatavigalajjala — Pravaha Pavita Sthale',
        meaning: 'With rivers flowing from his matted locks, wearing serpents as garland — Shiva dances',
        color: '#c084fc',
        secondColor: '#7c3aed',
        audioSrc: 'https://ik.imagekit.io/rcsesr4xf/Shiva-Tandav.mp3',
        imageBg: 'https://images.unsplash.com/photo-1447433819943-74a20887a81e?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~8 min',
        isLong: false,
        category: 'Stotra',
        emoji: '🔱',
    },
    {
        id: 'vishnu-sahasranamam',
        name: 'Vishnu Sahasranamam',
        nameHi: 'विष्णु सहस्रनाम',
        deity: 'Vishnu — The Preserver',
        deityHi: 'विष्णु — पालक ईश्वर',
        mantraText: 'ॐ नमो भगवते वासुदेवाय\nविश्वं विष्णुर्वषट्कारो\nभूतभव्यभवत्प्रभुः ॥',
        transliteration: 'Om Namo Bhagavate Vasudevaya',
        meaning: 'A thousand names of Lord Vishnu who is the universe itself',
        color: '#38bdf8',
        secondColor: '#0369a1',
        // This is a real content video — plays as video reel
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/VISHNU%20SAHASRANAMAM%20_%20Madhubanti%20Bagchi%20%26%20Siddharth%20Bhavsar%20_%20Stotra%20For%20Peace%20%26%20Divine%20Blessings.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/VISHNU%20SAHASRANAMAM%20_%20Madhubanti%20Bagchi%20%26%20Siddharth%20Bhavsar%20_%20Stotra%20For%20Peace%20%26%20Divine%20Blessings.mp4',
        imageBg: 'https://images.unsplash.com/photo-1517816743773-6e0d765cdc96?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~52 min',
        isLong: true,
        category: 'Sahasranamam',
        emoji: '🪷',
    },
    {
        id: 'om-namah-shivaya',
        name: 'Om Namah Shivaya',
        nameHi: 'ॐ नमः शिवाय',
        deity: 'Shiva — The Inner Self',
        deityHi: 'शिव — अंतरात्मा',
        mantraText: 'ॐ नमः शिवाय\nनमः शिवाय\nशिवाय नमः ॥',
        transliteration: 'Om Namah Shivaya — I bow to the inner Self',
        meaning: 'I bow to Lord Shiva — the five elements, the inner self and universal consciousness',
        color: '#a78bfa',
        secondColor: '#4f46e5',
        audioSrc: '/audio/Om%20Namah%20Shivaya.mp3',
        imageBg: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~5 min',
        isLong: false,
        category: 'Mantra',
        emoji: '🛕',
    },
    {
        id: 'shanti-path',
        name: 'Shanti Path',
        nameHi: 'शांति पाठ (21 ब्राह्मण)',
        deity: 'Universal Peace',
        deityHi: 'सर्वलोक शांति',
        mantraText: 'ॐ असतो मा सद्गमय ।\nतमसो मा ज्योतिर्गमय ।\nमृत्योर्मा अमृतं गमय ।\nॐ शान्तिः शान्तिः शान्तिः ॥',
        transliteration: 'Asato Ma Sadgamaya — Lead me from untruth to truth',
        meaning: 'Lead me from ignorance to truth, from darkness to light, from death to immortality',
        color: '#34d399',
        secondColor: '#059669',
        audioSrc: 'https://ik.imagekit.io/rcsesr4xf/shanti-path.mp3',
        imageBg: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~10 min',
        isLong: false,
        category: 'Vedic Mantra',
        emoji: '✨',
    },
    {
        id: 'hanuman-chalisa',
        name: 'Hanuman Chalisa',
        nameHi: 'हनुमान चालीसा',
        deity: 'Hanuman — The Mighty',
        deityHi: 'हनुमान — बजरंगबली',
        mantraText: 'जय हनुमान ज्ञान गुण सागर ।\nजय कपीस तिहुँ लोक उजागर ॥\nराम दूत अतुलित बल धामा ।',
        transliteration: 'Jai Hanuman Gyan Gun Sagar — Glory to Hanuman',
        meaning: 'Victory to Hanuman, ocean of wisdom and virtue, the radiant one of the three worlds',
        color: '#f97316',
        secondColor: '#c2410c',
        audioSrc: '/audio/Powerful Hanuman Chalisa  HanuMan  Teja Sajja  Saicharan  Hanuman Jayanti Song  Jai Hanuman.mp3',
        imageBg: '/images/hanumanji.png',
        durationLabel: '~7 min',
        isLong: false,
        category: 'Chalisa',
        emoji: '🙏',
    },
    {
        id: 'dainik-agnihotra',
        name: 'Dainik Agnihotra',
        nameHi: 'दैनिक अग्निहोत्र',
        deity: 'Agni — Sacred Fire',
        deityHi: 'अग्नि — पावन अग्नि',
        mantraText: 'भूरग्नये स्वाहा ।\nभुवरग्नये स्वाहा ।\nस्वरग्नये स्वाहा ॥',
        transliteration: 'Bhur Agnaye Svaha — I offer to the sacred fire',
        meaning: 'Offering to the sacred fire of earth, sky and heaven — the daily ritual of purification',
        color: '#ef4444',
        secondColor: '#b91c1c',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/DainikAgnihotra.mp3?updatedAt=1771246817070',
        imageBg: 'https://images.unsplash.com/photo-1574169208507-84376144848b?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~15 min',
        isLong: true,
        category: 'Vedic Ritual',
        emoji: '🔥',
    },
    {
        id: 'rudrashtakam',
        name: 'Rudrashtakam',
        nameHi: 'रुद्राष्टकम्',
        deity: 'Rudra — The Fierce Shiva',
        deityHi: 'रुद्र — भगवान शिव',
        mantraText: 'नमामीशमीशान निर्वाणरूपं\nविभुं व्यापकं ब्रह्मवेदस्वरूपम् ।\nनिजं निर्गुणं निर्विकल्पं निरीहं\nचिदाकाशमाकाशवासं भजेऽहम् ॥',
        transliteration: 'Namami Isham Ishan Nirvana Rupam',
        meaning: 'I bow to Shiva who is the essence of liberation, all-pervading and the form of Vedas',
        color: '#60a5fa',
        secondColor: '#1d4ed8',
        audioSrc: '/audio/Agam - Rudrashtakam  रदरषटकम  Most POWERFUL Shiva Mantras Ever  Lyrical Video  Shiv.mp3',
        imageBg: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~8 min',
        isLong: false,
        category: 'Stotra',
        emoji: '🏔️',
    },
    {
        id: 'brahma-yagya',
        name: 'Brahma Yagya',
        nameHi: 'ब्रह्मयज्ञ',
        deity: 'Brahma — The Creator',
        deityHi: 'ब्रह्मा — सृष्टिकर्ता',
        mantraText: 'ॐ शन्नो मित्रः शं वरुणः ।\nशन्नो भवत्वर्यमा ।\nशन्न इन्द्रो बृहस्पतिः ॥',
        transliteration: 'Om Shanno Mitrah Sham Varunah',
        meaning: 'May the Sun be gracious to us, may Varuna be gracious — universal prayer for peace',
        color: '#fbbf24',
        secondColor: '#b45309',
        audioSrc: 'https://ik.imagekit.io/rcsesr4xf/BrahmaYagya.mp3',
        imageBg: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~20 min',
        isLong: true,
        category: 'Vedic Yagya',
        emoji: '🪔',
    },
    {
        id: 'kaal-bhairav',
        name: 'Kaal Bhairav Ashtakam',
        nameHi: 'काल भैरव अष्टकम्',
        deity: 'Kaal Bhairav — Lord of Time',
        deityHi: 'काल भैरव — कालदेवता',
        mantraText: 'देवराजसेव्यमानपावनाङ्घ्रिपङ्कजं\nव्यालयज्ञसूत्रमिन्दुशेखरं कृपाकरम् ।\nनारदादियोगिवृन्दवन्दितं दिगम्बरं\nकाशिकापुराधिनाथकालभैरवं भजे ॥',
        transliteration: 'Devaraja Sevyamana Pavana Anghri Pankajam',
        meaning: 'I worship Kaal Bhairav of Kashi, worshipped by the king of gods, the Lord of Time',
        color: '#818cf8',
        secondColor: '#4f46e5',
        // This is a real content video
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/Kaal%20Bhairav%20Ashtakam%20_%20Tanuku%20Sisters%20_%20@DivineDharohar.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/Kaal%20Bhairav%20Ashtakam%20_%20Tanuku%20Sisters%20_%20@DivineDharohar.mp4',
        imageBg: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~6 min',
        isLong: false,
        category: 'Ashtakam',
        emoji: '⏳',
    },
    {
        id: 'maheshvara-sutram',
        name: 'Maheshvara Sutram',
        nameHi: 'माहेश्वर सूत्रम्',
        deity: 'Maheshvara — Supreme Shiva',
        deityHi: 'महेश्वर — परम शिव',
        mantraText: 'अ इ उ ण् ।\nऋ ॡ क् ।\nए ओ ङ् ।\nऐ औ च् ।',
        transliteration: 'The Primal Sounds of Creation — 14 Maheshvara Sutras',
        meaning: 'The sacred sounds that Shiva produced from his cosmic drum at the beginning of creation',
        color: '#c084fc',
        secondColor: '#9333ea',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/Most%20powerful%20Maheshvara%20Su%CC%84tram%20_%20the%20primal%20sound%20of%20creation.%E0%A4%AE%E0%A4%BE%E0%A4%B9%E0%A5%87%E0%A4%B6%E0%A5%8D%E0%A4%B5%E0%A4%B0%20%E0%A4%B8%E0%A5%82%E0%A4%A4%E0%A5%8D%E0%A4%B0%E0%A4%AE%E0%A5%8D%20_%20%E0%A4%9C%E0%A4%BF%E0%A4%B8%E0%A4%B8%E0%A5%87%20%E0%A4%B8%E0%A4%AE%E0%A5%8D%E0%A4%AA%E0%A5%82%E0%A4%B0%E0%A5%8D%E0%A4%A3.mp4',
        imageBg: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~3 min',
        isLong: false,
        category: 'Vedic Mantra',
        emoji: '🌀',
    },
    // ── Dhyan Kshetra exclusive items ──────────────────────────────────────────
    {
        id: 'guru-shishya',
        name: 'Guru Shishya Mantra',
        nameHi: 'गुरु शिष्य मंत्र',
        deity: 'Gurukul — Sacred Bond',
        deityHi: 'गुरुकुल — पवित्र बंधन',
        mantraText: 'ॐ सह नाववतु ।\nसह नौ भुनक्तु ।\nसह वीर्यं करवावहै ॥',
        transliteration: 'Om Saha Nau Avatu — May we be protected together',
        meaning: 'May we be protected together, nourished together and work with great energy together',
        color: '#fbbf24',
        secondColor: '#d97706',
        audioSrc: '/audio/Om_Sahana_Vavatu_Shanti_Mantra.mp3',
        imageBg: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~5 min',
        isLong: false,
        category: 'Vedic Mantra',
        emoji: '🪔',
    },
    {
        id: 'agnihotra-shantipath',
        name: 'Agnihotra Shantipath',
        nameHi: 'अग्निहोत्र शांतिपाठ',
        deity: 'Agni — Universal Peace',
        deityHi: 'अग्नि — सर्वलोक शांति',
        mantraText: 'ॐ स्वस्ति न इन्द्रो वृद्धश्रवाः ।\nस्वस्ति नः पूषा विश्ववेदाः ।\nस्वस्ति नस्तार्क्ष्यो अरिष्टनेमिः ॥',
        transliteration: 'Om Svasti Na Indro — May great Indra bless us',
        meaning: 'May Indra bless us, may Pusha the Sun bless us — Vedic chants for universal peace and well-being',
        color: '#f97316',
        secondColor: '#c2410c',
        audioSrc: '/audio/Agnihotra_Shantipath_-_Vedic_Chants_for_Universal_Peace_and_Well-Being_part_2_(mp3.pm).mp3',
        imageBg: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~12 min',
        isLong: false,
        category: 'Vedic Ritual',
        emoji: '🔥',
    },
    {
        id: 'rudri-path',
        name: 'Complete Rudri Path',
        nameHi: 'सम्पूर्ण रुद्री पाठ',
        deity: 'Rudra — 21 Brahmins Chanting',
        deityHi: 'रुद्र — 21 ब्राह्मण गायन',
        mantraText: 'नमस्ते रुद्र मन्यवे\nउतो त इषवे नमः ।\nनमस्ते अस्तु धन्वने\nबाहुभ्यामुत ते नमः ॥',
        transliteration: 'Namaste Rudra Manyave — Salutations to Rudra',
        meaning: 'Salutations to the fierce Rudra — complete Rudri Path chanted in sacred unison by 21 Brahmins',
        color: '#818cf8',
        secondColor: '#4f46e5',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/Complete%20Rudri%20Path%20with%20Lyrics%20_%20Vedic%20Chanting%20by%2021%20Brahmins.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/Complete%20Rudri%20Path%20with%20Lyrics%20_%20Vedic%20Chanting%20by%2021%20Brahmins.mp4',
        imageBg: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~1 hr',
        isLong: true,
        category: 'Vedic Chanting',
        emoji: '🏔️',
    },
    {
        id: 'shiv-shakti-energy',
        name: 'Shiv Shakti Energy',
        nameHi: 'शिव शक्ति ऊर्जा',
        deity: 'Shiva & Shakti — Cosmic Energy',
        deityHi: 'शिव-शक्ति — ब्रह्मांडीय ऊर्जा',
        mantraText: 'हर हर महादेव\nॐ नमः शिवाय\nशिव शक्ति ॐ ॥',
        transliteration: 'Har Har Mahadev — Feel the Divine Energy',
        meaning: 'Feel the divine cosmic energy of Shiva and Shakti flowing through you in every breath',
        color: '#a78bfa',
        secondColor: '#7c3aed',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/Just%20feel%20the%20energy%20____Follow%20@fmccreators%20for%20more_%E0%A4%B9%E0%A4%B0%20%E0%A4%B9%E0%A4%B0%20%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%A6%E0%A5%87%E0%A4%B5%20__%E0%A4%9C%E0%A4%AF%20%E0%A4%B6%E0%A4%82%E0%A4%95%E0%A4%B0%20___Do%20like.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/Just%20feel%20the%20energy%20____Follow%20@fmccreators%20for%20more_%E0%A4%B9%E0%A4%B0%20%E0%A4%B9%E0%A4%B0%20%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%A6%E0%A5%87%E0%A4%B5%20__%E0%A4%9C%E0%A4%AF%20%E0%A4%B6%E0%A4%82%E0%A4%95%E0%A4%B0%20___Do%20like.mp4',
        imageBg: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~3 min',
        isLong: false,
        category: 'Shakti',
        emoji: '⚡',
    },
    {
        id: 'ardhanarishvara',
        name: 'Ardhanarishvara',
        nameHi: 'अर्धनारीश्वर',
        deity: 'Ardhanarishvara — Half Woman Lord',
        deityHi: 'अर्धनारीश्वर — शिव-शक्ति एकत्व',
        mantraText: 'ॐ अर्धनारीश्वराय नमः ।\nशिव शक्त्यात्मने नमः ।\nपरमशिवाय नमः ॥',
        transliteration: 'Om Ardhanarishvaraya Namah',
        meaning: 'The Lord who is half-woman — perfect synthesis of masculine and feminine cosmic energies',
        color: '#f472b6',
        secondColor: '#9333ea',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/The%20_Lord%20who%20is%20half%20woman_%20signifies%20the%20perfect%20synthesis%20of%20masculine%20and%20feminine%20energies,.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/The%20_Lord%20who%20is%20half%20woman_%20signifies%20the%20perfect%20synthesis%20of%20masculine%20and%20feminine%20energies,.mp4',
        imageBg: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~2 min',
        isLong: false,
        category: 'Shakti Mantra',
        emoji: '🌸',
    },
    {
        id: 'shiv-swarnamala',
        name: 'Shiv Swarnamala Stuti',
        nameHi: 'शिव स्वर्णमाला स्तुति',
        deity: 'Mahadev — Golden Garland Hymn',
        deityHi: 'महादेव — स्वर्णमाला स्तुति',
        mantraText: 'ॐ नमः शिवाय शुभाय\nशङ्करप्रियाय स्वाहा\nशिव स्वर्णमाला स्तुति ॥',
        transliteration: 'Om Namah Shivaya Shubhaya — Shiv Swarnamala',
        meaning: 'The golden garland hymn to Lord Shiva — each verse a golden bead of pure devotion',
        color: '#fbbf24',
        secondColor: '#b45309',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/Shiv%20Swarnamala%20Stuti%20_%E2%9D%A4%EF%B8%8F%20I%20Verse%20-%207%20_.Follow%20@aumm_namah_shivay%20for%20more%20%E2%9D%A4%EF%B8%8F%20.._mahadev%20_shiv.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/Shiv%20Swarnamala%20Stuti%20_%E2%9D%A4%EF%B8%8F%20I%20Verse%20-%207%20_.Follow%20@aumm_namah_shivay%20for%20more%20%E2%9D%A4%EF%B8%8F%20.._mahadev%20_shiv.mp4',
        imageBg: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~4 min',
        isLong: false,
        category: 'Stotra',
        emoji: '🏅',
    },
    {
        id: 'nad-chikitsa',
        name: 'Nad Chikitsa — Sound Healing',
        nameHi: 'नाद चिकित्सा',
        deity: 'Nada Brahman — Sound is God',
        deityHi: 'नादब्रह्म — ध्वनि ईश्वर है',
        mantraText: 'नाद ब्रह्म विश्वस्वरूपम् ।\nनाद से उत्पन्न जगत् ।\nनाद चिकित्सा — ध्वनि उपचार ॥',
        transliteration: 'Nada Brahma Vishvasvarupam — Sound is the form of God',
        meaning: 'Sound has power to heal — ancient wisdom of sound therapy and healing frequencies for the soul',
        color: '#22d3ee',
        secondColor: '#0891b2',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/Most%20people%20don_t%20realize%20it,%20but%20sound%20has%20the%20power%20to%20heal%20-%20or%20harm.%20There_s%20a%20reason%20why%20an.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/Most%20people%20don_t%20realize%20it,%20but%20sound%20has%20the%20power%20to%20heal%20-%20or%20harm.%20There_s%20a%20reason%20why%20an.mp4',
        imageBg: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~3 min',
        isLong: false,
        category: 'Sound Healing',
        emoji: '🎶',
    },
    {
        id: 'mahadev-nav-varsh',
        name: 'Mahadev — Nav Varsh',
        nameHi: 'महादेव — नव वर्ष',
        deity: 'Mahadev — New Year Blessings',
        deityHi: 'महादेव — नव वर्ष आशीर्वाद',
        mantraText: 'हर हर महादेव\nनव वर्ष की हार्दिक\nशुभकामनाएं ॥',
        transliteration: 'Har Har Mahadev — Nav Varsh Shubhkamnaen',
        meaning: 'New Year blessings from Lord Shiva — may the new year bring divine light and transformation',
        color: '#f97316',
        secondColor: '#c2410c',
        audioSrc: 'https://ik.imagekit.io/aup4wh6lq/%E0%A4%86%E0%A4%AA%20%E0%A4%B8%E0%A4%AD%E0%A5%80%20%E0%A4%95%E0%A5%8B%20%E0%A4%A8%E0%A4%B5%20%E0%A4%B5%E0%A4%B0%E0%A5%8D%E0%A4%B7%20%E0%A4%95%E0%A5%80%20%E0%A4%B9%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%A6%E0%A4%BF%E0%A4%95%20%E0%A4%AC%E0%A4%A7%E0%A4%BE%E0%A4%88%20%E0%A4%8F%E0%A4%B5%E0%A4%82%20%E0%A4%B6%E0%A5%81%E0%A4%AD%E0%A4%95%E0%A4%BE%E0%A4%AE%E0%A4%A8%E0%A4%BE%E0%A4%8F%E0%A4%81_%E0%A4%B9%E0%A4%B0%20%E0%A4%B9%E0%A4%B0%20%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%A6%E0%A5%87%E0%A4%B5____.mp4',
        videoSrc: 'https://ik.imagekit.io/aup4wh6lq/%E0%A4%86%E0%A4%AA%20%E0%A4%B8%E0%A4%AD%E0%A5%80%20%E0%A4%95%E0%A5%8B%20%E0%A4%A8%E0%A4%B5%20%E0%A4%B5%E0%A4%B0%E0%A5%8D%E0%A4%B7%20%E0%A4%95%E0%A5%80%20%E0%A4%B9%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%A6%E0%A4%BF%E0%A4%95%20%E0%A4%AC%E0%A4%A7%E0%A4%BE%E0%A4%88%20%E0%A4%8F%E0%A4%B5%E0%A4%82%20%E0%A4%B6%E0%A5%81%E0%A4%AD%E0%A4%95%E0%A4%BE%E0%A4%AE%E0%A4%A8%E0%A4%BE%E0%A4%8F%E0%A4%81_%E0%A4%B9%E0%A4%B0%20%E0%A4%B9%E0%A4%B0%20%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%A6%E0%A5%87%E0%A4%B5____.mp4',
        imageBg: 'https://images.unsplash.com/photo-1471931452361-f5ff1faa15ad?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~2 min',
        isLong: false,
        category: 'Celebration',
        emoji: '🎊',
    },
    {
        id: 'mahashivratri-special',
        name: 'Mahashivratri Special',
        nameHi: 'महाशिवरात्रि विशेष',
        deity: 'Shiva — The Great Night',
        deityHi: 'शिव — महारात्रि दर्शन',
        mantraText: 'ॐ नमः शिवाय\nमहाशिवरात्रि की\nहार्दिक शुभकामनाएं ॥',
        transliteration: 'Om Namah Shivaya — Mahashivratri Special',
        meaning: 'On the great night of Shiva, we offer salutations — transcend darkness and attain liberation',
        color: '#c084fc',
        secondColor: '#7c3aed',
        audioSrc: '/videos/mahashivratri_darshan.mp4',
        videoSrc: '/videos/mahashivratri_darshan.mp4',
        imageBg: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~5 min',
        isLong: false,
        category: 'Festival',
        emoji: '🔱',
    },
    {
        id: 'shri-suktam',
        name: 'Shri Suktam',
        nameHi: 'श्री सूक्तम्',
        deity: 'Lakshmi — Goddess of Abundance',
        deityHi: 'लक्ष्मी — समृद्धि देवी',
        mantraText: 'हिरण्यवर्णां हरिणीं\nसुवर्णरजतस्रजाम् ।\nचन्द्रां हिरण्मयीं लक्ष्मीं\nजातवेदो म आवह ॥',
        transliteration: 'Hiranyavarnam Harineem — Golden Lakshmi come to me',
        meaning: 'O golden Lakshmi, wearing gold and silver garlands — bless us with divine abundance',
        color: '#fbbf24',
        secondColor: '#d97706',
        audioSrc: '/audio/Challakere_Brothers_vedic_chanting_-_Shri_suktam_(mp3.pm).mp3',
        imageBg: 'https://images.unsplash.com/photo-1600959907703-571a4f1f9fc4?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~12 min',
        isLong: false,
        category: 'Suktam',
        emoji: '🪷',
    },
    {
        id: 'narayana-suktam',
        name: 'Narayana Suktam',
        nameHi: 'नारायण सूक्तम्',
        deity: 'Narayana — Universal Cosmic Prayer',
        deityHi: 'नारायण — ब्रह्मांड प्रार्थना',
        mantraText: 'ॐ सहस्रशीर्षा पुरुषः\nसहस्राक्षः सहस्रपात् ।\nस भूमिं विश्वतो वृत्वा\nअत्यतिष्ठद्दशाङ्गुलम् ॥',
        transliteration: 'Om Sahasrashirsha Purushah — The Universal Cosmic Being',
        meaning: 'The Universal Cosmic Person with a thousand heads and eyes — Narayana pervades the universe',
        color: '#38bdf8',
        secondColor: '#0369a1',
        audioSrc: '/audio/Anant_-_a_collection_of_vedic_chants_-_05._Narayana_Suktam_(mp3.pm).mp3',
        imageBg: 'https://images.unsplash.com/photo-1474418397713-003ec9403fe5?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~15 min',
        isLong: false,
        category: 'Suktam',
        emoji: '🪷',
    },
    {
        id: 'virija-homa',
        name: 'Virija Homa Mantra',
        nameHi: 'विरजा होम मंत्र',
        deity: 'Agni — Sacred Fire Ritual',
        deityHi: 'अग्नि — यज्ञ अनुष्ठान',
        mantraText: 'ॐ विरजा होम मंत्र\nपावन अग्नि में\nआहुति समर्पण ॥',
        transliteration: 'Om Virija Homa Mantra — Sacred Fire Offering',
        meaning: 'The sacred Virija Homa fire ritual — purification through fire and sacred Vedic offerings',
        color: '#ef4444',
        secondColor: '#b91c1c',
        audioSrc: '/audio/Virija Homa Mantra  Uma Mohan  Promod Shanker  Times Music Spiritual.mp3',
        imageBg: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=1400&fit=crop&q=90',
        durationLabel: '~10 min',
        isLong: false,
        category: 'Vedic Ritual',
        emoji: '🪔',
    },
];
